---UPDATES PARA UNIFICAR NOMBRES
UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'ALICIA OVIEDO'
WHERE FUNCIONARIO = 'ALICIA OVIEDO VELASQUEZ'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'ANDREA BILBAO'
WHERE FUNCIONARIO = 'ANDREA BILBAO BRICEÑO'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'GIOVANNA HERRERA'
WHERE FUNCIONARIO = 'GIOVANNA HERRERA MATHEWS'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'GUSTAVO PALLETE'
WHERE FUNCIONARIO = 'GUSTAVO PALLETE ALFERANO'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'JULY GARCIA'
WHERE FUNCIONARIO = 'JULY GARCIA ALCANTARA'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'KATHERIN RAMOS'
WHERE FUNCIONARIO = 'KATHERIN RAMOS CCAMA'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'MARGIORY ELIAS'
WHERE FUNCIONARIO = 'MARGIORY ELIAS BENAVIDES'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'ROSA MALDONADO'
WHERE FUNCIONARIO = 'ROSA MALDONADO FIGUREOA'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'ROXANA QUISPE'
WHERE FUNCIONARIO = 'ROXANA QUISPE CHAVEZ'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'DAVID BORJA'
WHERE FUNCIONARIO = 'DAVID BORJA HERENCIA'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'OFICINA CAÑETE'
WHERE FUNCIONARIO = 'PROSEVA CAÑETE'
-----------------ld
UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'EVELYN LOJA'
WHERE FUNCIONARIO = 'EVELYN LOJA PINEDO'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'JERSON ALVA'
WHERE FUNCIONARIO = 'JERSON ALVA FARFAN'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'MARGARITA CHINGA'
WHERE FUNCIONARIO = 'MARGARITA CHINGA ESPINOZA'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'OFICINA CAÑETE'
WHERE FUNCIONARIO = 'PROSEVA CAÑETE'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'LUIS CASTAÑEDA'
WHERE FUNCIONARIO LIKE '%LUIS CASTAÑEDA%'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'LUIS BUSTAMANTE'
WHERE FUNCIONARIO LIKE '%LUIS ALBERTO BUSTAMANTE GONZALES%'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'LUIS BUSTAMANTE'
WHERE FUNCIONARIO LIKE 'JORGE LUIS ARAGON HUAIHUA'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'CESAR MEDINA'
WHERE FUNCIONARIO LIKE '%CESAR MEDINA%'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'ALEJANDRO HUAMAN'
WHERE FUNCIONARIO LIKE '%ALEJANDRO HUAMAN%'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'FIGARI VEGA'
WHERE FUNCIONARIO LIKE '%FIGARI VEGA%'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'JEAN BRAVO'
WHERE FUNCIONARIO LIKE '%JEAN KARLHO BRAVO MATIAS%'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'JIMN MENDOZA'
WHERE FUNCIONARIO LIKE '%JIMN MENDOZA%'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'JOSE SANCHEZ'
WHERE FUNCIONARIO LIKE '%JOSE SANCHEZ%'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'MILTON JUAREZ'
WHERE FUNCIONARIO LIKE '%MILTON MERLYN JUAREZ HORNA%'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'VICTOR FARFAN'
WHERE FUNCIONARIO LIKE '%VICTOR FARFAN%'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'DENNIS TERRONES'
WHERE FUNCIONARIO LIKE '%DENIS TORRES%'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'DENNIS TERRONES'
WHERE FUNCIONARIO LIKE '%DENIS TERRONES%'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'ANTHONNY OSORIO'
WHERE FUNCIONARIO LIKE '%ANTHONY OSORIO%'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'DAVID BORJA'
WHERE FUNCIONARIO LIKE '%DAVID BORJA%'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'GIOVANNA HERRERA'
WHERE FUNCIONARIO LIKE '%GIOVANA HERRERA%'

-----------PROSEVAS-------------
UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'PROSEVA AREQUIPA'
WHERE FUNCIONARIO LIKE '%AREQUIPA PROSEVA%'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'PROSEVA CHICLAYO'
WHERE FUNCIONARIO LIKE '%CHICLAYO PROSEVA%'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'PROSEVA CUSCO'
WHERE FUNCIONARIO LIKE '%CUSCO PROSEVA%'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'PROSEVA CHINCHA'
WHERE FUNCIONARIO LIKE '%CHINCHA PROSEVA%'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'PROSEVA HUACHO'
WHERE FUNCIONARIO LIKE '%HUACHO PROSEVA%'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'PROSEVA JAEN'
WHERE FUNCIONARIO LIKE '%JAEN PROSEVA%'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'PROSEVA ICA'
WHERE FUNCIONARIO LIKE '%ICA PROSEVA%'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'PROSEVA PIURA'
WHERE FUNCIONARIO LIKE '%PIURA PROSEVA%'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'PROSEVA TACNA'
WHERE FUNCIONARIO LIKE '%TACNA PROSEVA%'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'PROSEVA TRUJILLO'
WHERE FUNCIONARIO LIKE '%TRUJILLO PROSEVA%'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'PROSEVA TUMBES'
WHERE FUNCIONARIO LIKE '%TUMBES PROSEVA%'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'OFICINA CAÑETE'
WHERE FUNCIONARIO LIKE '%CAÑETE OFICINA%'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'JAQUELINE CHUQUISUTA'
WHERE FUNCIONARIO LIKE '%YAQUELINE CHUQUISUTA%'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'JAQUELINE LIÑAN'
WHERE FUNCIONARIO LIKE '%JAQUELINE LIÑAN MORE%'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'JAQUELINE LIÑAN'
WHERE FUNCIONARIO LIKE '%JACQUELINE LIÑAN%'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'CRISTIAN ZAMORA'
WHERE FUNCIONARIO LIKE 'CRISTIAN ZAMORA PERLECHE'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'DHAYANNA CHIRE'
WHERE FUNCIONARIO LIKE 'DAYANA CHIRE'

UPDATE reportes_diana..DIANA_REPORTE
SET FUNCIONARIO = 'LUZ CABALLERO'
WHERE FUNCIONARIO LIKE 'LUZ MARINA CABALLERO'

--UPDATE reportes_diana..DIANA_REPORTE
--SET FUNCIONARIO = 'ALICIA OVIEDO'
--WHERE FUNCIONARIO = 'ALICIA OVIEDO VELASQUEZ'